export const GET_TRAINS_PUNCTUALITIES = "GET_TRAINS_PUNCTUALITIES";
export const GET_TRAINS_PUNCTUALITIES_SUCCESS =
  "GET_TRAINS_PUNCTUALITIES_SUCCESS";
export const GET_TRAINS_PUNCTUALITIES_FAIL = "GET_TRAINS_PUNCTUALITIES_FAIL";
export const ADD_TRAINS_PUNCTUALITY = "ADD_TRAINS_PUNCTUALITY";
export const ADD_TRAINS_PUNCTUALITY_SUCCESS = "ADD_TRAINS_PUNCTUALITY_SUCCESS";
export const ADD_TRAINS_PUNCTUALITY_FAIL = "ADD_TRAINS_PUNCTUALITY_FAIL";
export const EDIT_TRAINS_PUNCTUALITY = "EDIT_TRAINS_PUNCTUALITY";
export const EDIT_TRAINS_PUNCTUALITY_SUCCESS =
  "EDIT_TRAINS_PUNCTUALITY_SUCCESS";
export const EDIT_TRAINS_PUNCTUALITY_FAIL = "EDIT_TRAINS_PUNCTUALITY_FAIL";
export const DELETE_TRAINS_PUNCTUALITY = "DELETE_TRAINS_PUNCTUALITY";
export const DELETE_TRAINS_PUNCTUALITY_SUCCESS =
  "DELETE_TRAINS_PUNCTUALITY_SUCCESS";
export const DELETE_TRAINS_PUNCTUALITY_FAIL = "DELETE_TRAINS_PUNCTUALITY_FAIL";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
