/* PASSENGER ROAD TRANSPORT DATA */
export const GET_PASSENGER_ROAD_TRANSPORT_DATA = "GET_PASSENGER_ROAD_TRANSPORT_DATA"
export const GET_PASSENGER_ROAD_TRANSPORT_DATA_SUCCESS = "GET_PASSENGER_ROAD_TRANSPORT_DATA_SUCCESS"
export const GET_PASSENGER_ROAD_TRANSPORT_DATA_FAIL = "GET_PASSENGER_ROAD_TRANSPORT_DATA_FAIL"

/* FREIGHT ROAD TRANSPORT DATA */
export const GET_FREIGHT_ROAD_TRANSPORT_DATA = "GET_FREIGHT_ROAD_TRANSPORT_DATA"
export const GET_FREIGHT_ROAD_TRANSPORT_DATA_SUCCESS = "GET_FREIGHT_ROAD_TRANSPORT_DATA_SUCCESS"
export const GET_FREIGHT_ROAD_TRANSPORT_DATA_FAIL = "GET_FREIGHT_ROAD_TRANSPORT_DATA_FAIL"