export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS =
  "EDIT_USERS_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS =
  "DELETE_USERS_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
